# Usamos una imagen oficial de Elixir
FROM elixir:1.15

# Instalamos inotify-tools (CRÍTICO para que funcione el Hot Reload en Linux/Docker)
# También instalamos build-essential por si hay que compilar dependencias C
RUN apt-get update && \
    apt-get install -y inotify-tools build-essential postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalamos Hex y Rebar (gestores de paquetes de Erlang/Elixir)
RUN mix local.hex --force && \
    mix local.rebar --force

# Comando por defecto (inicia el servidor)
CMD ["mix", "phx.server"]